package com.SixSense.queue;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.io.Closeable;
import java.util.concurrent.*;
import java.util.function.Supplier;

@Component
/*Manages all multi-threaded executables generated by the engine*/
public class WorkerQueue implements Closeable {
    private static final Logger logger = LogManager.getLogger(WorkerQueue.class);
    private final ExecutorService workerPool = Executors.newCachedThreadPool();
    private boolean isClosed = false;

    @Autowired
    private WorkerQueue(){

    }

    public <V> CompletableFuture<V> submit(Supplier<V> worker){
        if(this.isClosed){
            return CompletableFuture.failedFuture(new Exception("Cannot submit supplier to work queue - worker pool has been closed"));
        }else{
            return CompletableFuture.supplyAsync(worker, workerPool);
        }
    }

    public void submit(Runnable worker) throws Exception{
        if(this.isClosed){
            throw new Exception("Cannot submit runnable to work queue - worker pool has been closed");
        }
        workerPool.submit(worker);
    }

    public boolean isShutdown(){
        return workerPool.isShutdown();
    }

    @Override
    public void close() {
        this.workerPool.shutdownNow();
        this.isClosed = true;
        logger.info("WorkerQueue closed");
    }
}
